/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.1.2.RELEASE")
    implementation("com.h2database:h2:1.4.197")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.1.2.RELEASE")
}

group = "org.springframework.boot"
version = "1.0"
description = "Spring Boot Spring Data JPA"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

application {
    mainClass.set("com.mkyong.StartApplication")
}

tasks.test {
    useJUnitPlatform()
}
