/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import example.Result;
import org.kie.api.runtime.KieSession;
import org.kie.api.KieServices;
import org.kie.api.builder.*;
import org.kie.api.io.Resource;
import org.kie.api.io.ResourceType;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;
import org.kie.internal.builder.DecisionTableConfiguration;
import org.kie.internal.builder.DecisionTableInputType;
import org.kie.internal.builder.KnowledgeBuilderFactory;
import org.kie.internal.io.ResourceFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static KieServices kieServices=KieServices.Factory.get();

    public static void main(String[] args) {
        Result result = new Result();
        KieFileSystem kieFileSystem = kieServices.newKieFileSystem();

        kieFileSystem.write(ResourceFactory.newClassPathResource("rules/rule.drl"));

        KieBuilder kb = kieServices.newKieBuilder(kieFileSystem);
        kb.buildAll();
        KieModule kieModule = kb.getKieModule();

        KieContainer kContainer = kieServices.newKieContainer(kieModule.getReleaseId());

        KieSession ksession = kContainer.newKieSession();
        ksession.setGlobal("result", result);

        result.setId(10);
        result.setData("Joy");
        ksession.insert(result);

        ksession.fireAllRules();

        System.out.println(result.getData());
        System.out.println("Done");
    }

}
