/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("org.drools:drools-core:7.66.0.Final")
    implementation("org.drools:drools-metric:7.66.0.Final")
    implementation("org.drools:drools-compiler:7.66.0.Final")
    implementation("org.drools:drools-model-compiler:7.66.0.Final")
    implementation("org.drools:drools-decisiontables:7.66.0.Final")
    implementation("ch.qos.logback:logback-classic:1.1.+")


    //implementation("org.drools:drools-core:8.31.0.Final")
    //implementation("org.drools:drools-metric:8.31.0.Final")
    //implementation("org.drools:drools-compiler:8.31.0.Final")
    //implementation("org.drools:drools-model-compiler:8.31.0.Final")
    //implementation("org.drools:drools-decisiontables:8.31.0.Final")

}

application {
    // Define the main class for the application.
    mainClass.set("example.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
