/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import example.Result;
import org.kie.api.runtime.KieSession;
import org.kie.api.KieServices;
import org.kie.api.builder.*;
import org.kie.api.io.Resource;
import org.kie.api.io.ResourceType;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;
import org.kie.internal.builder.DecisionTableConfiguration;
import org.kie.internal.builder.DecisionTableInputType;
import org.kie.internal.builder.KnowledgeBuilderFactory;
import org.kie.internal.io.ResourceFactory;
import org.kie.api.runtime.rule.FactHandle;

import java.util.HashMap;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static KieServices kieServices=KieServices.Factory.get();

    public static void main(String[] args) {
        KieFileSystem kieFileSystem = kieServices.newKieFileSystem();

        kieFileSystem.write(ResourceFactory.newClassPathResource("rules/rule1.drl"));

        KieBuilder kb = kieServices.newKieBuilder(kieFileSystem);
        kb.buildAll();
        KieModule kieModule = kb.getKieModule();

        KieContainer kContainer = kieServices.newKieContainer(kieModule.getReleaseId());

        KieSession ksession = kContainer.newKieSession();

        String[] names = new String[]{"kitchen", "bedroom", "office", "livingroom"};
        Map<String, Room> name2room = new HashMap<String, Room>();
        for( String name: names ) {
            Room room = new Room(name);
            name2room.put(name, room);
            ksession.insert(room);

            Sprinkler sprinkler = new Sprinkler(room);
            ksession.insert(sprinkler);
        }

        System.out.println("=======================");
        ksession.fireAllRules();

        Fire kitchenFire = new Fire(name2room.get("kitchen"));
        Fire officeFire = new Fire(name2room.get("office"));

        FactHandle kitchenFireHandle = ksession.insert(kitchenFire);
        FactHandle officeFireHandle = ksession.insert(officeFire);

        System.out.println("=======================");
        ksession.fireAllRules();

        ksession.delete( kitchenFireHandle );
        ksession.delete( officeFireHandle );

        System.out.println("=======================");
        ksession.fireAllRules();

        System.out.println("Done");
    }
}
