/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package simple

import java.util.List;
import java.util.Arrays;

import org.apache.spark.SparkConf;
import org.apache.spark.broadcast.Broadcast;
//import org.apache.spark.sql.SparkSession

import org.kie.api.KieBase;
import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.StatelessKieSession;
import org.kie.api.internal.command.CommandFactory;

object App {
  case class Applicant(index: Int, fname: String, lname: String, n1: Int, n2:Int)

  def main(args : Array[String]): Unit = {
    var inputData = List(
      Applicant(1, "John", "Doe", 10000, 568)
      )
  }
}
