spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hiberate.dll-auto: update
    show-sql: true